# Generated by Django 4.1.1 on 2022-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0002_server_server_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTotalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('totalinfo', models.TextField(max_length=10000, verbose_name='totalinfo')),
            ],
            options={
                'verbose_name': 'ServerTotalinfo',
                'managed': True,
            },
        ),
    ]
