# Generated by Django 4.1.1 on 2022-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0008_remove_servertotalinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertotalinfo',
            name='totalinfo',
            field=models.TextField(verbose_name='totalinfo'),
        ),
    ]
